### ISSUE TITLE
Cannot Set Calendar Date When Executing Your Sample Code???

### ISSUE THREAD

**Issue by nghiatt1509** [anhtuanbw/calendar-plugin#5]
SLF4J: The requested version 1.7.16 by your slf4j binding is not compatible with [1.6]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
2019-06-04 18:28:15.525 INFO  c.k.katalon.core.main.TestCaseExecutor   - --------------------
2019-06-04 18:28:15.527 INFO  c.k.katalon.core.main.TestCaseExecutor   - START Test Cases/SetCalendarTestCase/SetCalendarOnGoogleFlight
2019-06-04 18:28:15.886 DEBUG testcase.SetCalendarOnGoogleFlight       - 1: openBrowser("https://www.google.com/flights")
2019-06-04 18:28:16.084 INFO  c.k.k.core.webui.driver.DriverFactory    - Starting 'Chrome' driver
2019-06-04 18:28:16.106 INFO  c.k.k.core.webui.driver.DriverFactory    - Action delay is set to 0 seconds
Starting ChromeDriver 2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a) on port 23455
Only local connections are allowed.
Jun 04, 2019 6:28:19 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
2019-06-04 18:28:19.403 INFO  c.k.k.core.webui.driver.DriverFactory    - sessionId = 25feb0b15f53677c88460163805db071
2019-06-04 18:28:19.424 INFO  c.k.k.core.webui.driver.DriverFactory    - browser = Chrome 74.0.3729.169
2019-06-04 18:28:19.424 INFO  c.k.k.core.webui.driver.DriverFactory    - platform = Windows 10
2019-06-04 18:28:19.426 INFO  c.k.k.core.webui.driver.DriverFactory    - seleniumVersion = 3.7.1
2019-06-04 18:28:19.427 INFO  c.k.k.core.webui.driver.DriverFactory    - proxyInformation = ProxyInformation{proxyOption=NO_PROXY, proxyServerType=HTTP, password=, proxyServerAddress=, proxyServerPort=0}
2019-06-04 18:28:21.183 DEBUG testcase.SetCalendarOnGoogleFlight       - 2: maximizeWindow()
2019-06-04 18:28:22.316 DEBUG testcase.SetCalendarOnGoogleFlight       - 3: delay(5)
2019-06-04 18:28:27.339 DEBUG testcase.SetCalendarOnGoogleFlight       - 4: click(findTestObject("GoogleFlight/startDate"))
2019-06-04 18:28:27.561 DEBUG testcase.SetCalendarOnGoogleFlight       - 5: delay(2)
2019-06-04 18:28:29.566 DEBUG testcase.SetCalendarOnGoogleFlight       - 6: com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword.setDate(findTestObject("GoogleFlight/calendar"), 10, 4, 2019, 2000, STOP_ON_FAILURE)
2019-06-04 18:29:40.137 ERROR c.k.k.core.keyword.internal.KeywordMain  - ❌ Cannot detect the date. (Root cause: com.kms.katalon.core.exception.StepFailedException: Cannot detect the date.
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.stepFailed(WebUIKeywordMain.groovy:64)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain$stepFailed$0.call(Unknown Source)
	at com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword$_setDate_closure1.doCall(SetDateCalendarKeyword.groovy:106)
	at com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword$_setDate_closure1.doCall(SetDateCalendarKeyword.groovy)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.runKeyword(WebUIKeywordMain.groovy:20)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain$runKeyword.call(Unknown Source)
	at com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword.setDate(SetDateCalendarKeyword.groovy:37)
	at com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword.invokeMethod(SetDateCalendarKeyword.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at SetCalendarOnGoogleFlight.run(SetCalendarOnGoogleFlight:26)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:331)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:322)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:301)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:293)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:227)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:114)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:105)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1559647693807.run(TempTestCase1559647693807.groovy:21)
)
2019-06-04 18:29:40.437 ERROR c.k.k.core.keyword.internal.KeywordMain  - ❌ Something wrong! Cannot set the calendar date. (Root cause: com.kms.katalon.core.exception.StepFailedException: Something wrong! Cannot set the calendar date.
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.stepFailed(WebUIKeywordMain.groovy:64)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.runKeyword(WebUIKeywordMain.groovy:26)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain$runKeyword.call(Unknown Source)
	at com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword.setDate(SetDateCalendarKeyword.groovy:37)
	at com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword.invokeMethod(SetDateCalendarKeyword.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at SetCalendarOnGoogleFlight.run(SetCalendarOnGoogleFlight:26)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:331)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:322)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:301)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:293)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:227)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:114)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:105)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1559647693807.run(TempTestCase1559647693807.groovy:21)
Caused by: com.kms.katalon.core.exception.StepFailedException: Cannot detect the date.
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.stepFailed(WebUIKeywordMain.groovy:64)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain$stepFailed$0.call(Unknown Source)
	at com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword$_setDate_closure1.doCall(SetDateCalendarKeyword.groovy:106)
	at com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword$_setDate_closure1.doCall(SetDateCalendarKeyword.groovy)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.runKeyword(WebUIKeywordMain.groovy:20)
	... 16 more
)
2019-06-04 18:29:40.439 ERROR k.k.c.m.CustomKeywordDelegatingMetaClass - ❌ Something wrong! Cannot set the calendar date.
2019-06-04 18:29:40.440 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword.setDate(findTestObject("GoogleFlight/calendar"), 10, 4, 2019, 2000, STOP_ON_FAILURE) FAILED.
Reason:
com.kms.katalon.core.exception.StepFailedException: Something wrong! Cannot set the calendar date.
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.stepFailed(WebUIKeywordMain.groovy:64)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.runKeyword(WebUIKeywordMain.groovy:26)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain$runKeyword.call(Unknown Source)
	at com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword.setDate(SetDateCalendarKeyword.groovy:37)
	at com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword.invokeMethod(SetDateCalendarKeyword.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at SetCalendarOnGoogleFlight.run(SetCalendarOnGoogleFlight:26)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:331)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:322)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:301)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:293)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:227)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:114)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:105)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1559647693807.run(TempTestCase1559647693807.groovy:21)
Caused by: com.kms.katalon.core.exception.StepFailedException: Cannot detect the date.
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.stepFailed(WebUIKeywordMain.groovy:64)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain$stepFailed$0.call(Unknown Source)
	at com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword$_setDate_closure1.doCall(SetDateCalendarKeyword.groovy:106)
	at com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword$_setDate_closure1.doCall(SetDateCalendarKeyword.groovy)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.runKeyword(WebUIKeywordMain.groovy:20)
	... 16 more

2019-06-04 18:29:40.442 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ Test Cases/SetCalendarTestCase/SetCalendarOnGoogleFlight FAILED.
Reason:
com.kms.katalon.core.exception.StepFailedException: Something wrong! Cannot set the calendar date.
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.stepFailed(WebUIKeywordMain.groovy:64)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.runKeyword(WebUIKeywordMain.groovy:26)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain$runKeyword.call(Unknown Source)
	at com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword.setDate(SetDateCalendarKeyword.groovy:37)
	at com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword.invokeMethod(SetDateCalendarKeyword.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at SetCalendarOnGoogleFlight.run(SetCalendarOnGoogleFlight:26)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:331)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:322)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:301)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:293)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:227)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:114)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:105)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1559647693807.run(TempTestCase1559647693807.groovy:21)
Caused by: com.kms.katalon.core.exception.StepFailedException: Cannot detect the date.
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.stepFailed(WebUIKeywordMain.groovy:64)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain$stepFailed$0.call(Unknown Source)
	at com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword$_setDate_closure1.doCall(SetDateCalendarKeyword.groovy:106)
	at com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword$_setDate_closure1.doCall(SetDateCalendarKeyword.groovy)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.runKeyword(WebUIKeywordMain.groovy:20)
	... 16 more

2019-06-04 18:29:40.443 INFO  c.k.katalon.core.main.TestCaseExecutor   - END Test Cases/SetCalendarTestCase/SetCalendarOnGoogleFlight

**Comment by anhtuanbw** [comment]
This issue happens when the script trying to select a date in the past (which not allowed on Google Flight - you are not allowed to book a flight in past 😂) 
So please update the script below:

`com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword.setDate(findTestObject("GoogleFlight/calendar"), 10, 4, 2019, 2000, STOP_ON_FAILURE)`

to 

`com.katalon.plugin.keyword.calendar.SetDateCalendarKeyword.setDate(findTestObject("GoogleFlight/calendar"), 10, 8, 2019, 2000, STOP_ON_FAILURE)`
